[project]
name = "programmers-guild"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.2.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
